name: movie_web_app
description: A movies and films searching platform, with overviews, reviews and recommandations.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  scroll_snap_list: ^0.9.1
  animations: ^2.0.2
  font_awesome_flutter: ^10.3.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  swipe_cards: ^1.0.0
  http: ^0.13.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  animated_text_kit: ^4.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit-Bold.ttf
        - asset: assets/fonts/Outfit-SemiBold.ttf

